WebMvcProjectTest1/WebMvcProjectTest1/Models/ErrorViewModel.cs
namespace WebMvcProjectTest1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebMvcProjectTest1/WebMvcProjectTest1/Controllers/BlogController.cs
using Business.Services;
using Domain.Entity;
using Microsoft.AspNetCore.Mvc;

namespace WebMvcProjectTest1.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        public BlogController(IBlogService service)
        {
            _blogService = service;
        }



        public IActionResult Index()
        {
            var blog = _blogService.GetAllBlog();
            return View(blog);
        }

        public IActionResult Details(int id)
        {
            var blog = _blogService.GetBlogById(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        
        public IActionResult Create()
        {
          return View();
        }

        [HttpPost]
        public IActionResult Create (Blog blog)
        {
            _blogService.AddBlog(blog);
            return RedirectToAction("Index");
        }

        public IActionResult Edit (int id)
        {
            var blog = _blogService.GetBlogById(id);
            if(blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        [HttpPost]
        public IActionResult Edit (Blog blog)
        {
            _blogService.UpdateBlog(blog);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var blog = _blogService.GetBlogById(id);
            if( blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            _blogService.DeleteBlog(id);
            return RedirectToAction("Index");
        }

    }
}

WebMvcProjectTest1/WebMvcProjectTest1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebMvcProjectTest1.Models;

namespace WebMvcProjectTest1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMvcProjectTest1/WebMvcProjectTest1/Views/Blog/Create.cshtml
@model Domain.Entity.Blog



<h1>Create Product</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
               
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="mt-4">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Blog/Delete.cshtml
@model Domain.Entity.Blog



<h1>Delete Blog</h1>


<hr />
<div>
    <h4>Are you sure you want to delete this?</h4>
    <div>

        <dl class="row">
            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-10">
               @Model.Name
            </dd>
            <dt class="col-sm-2">
               Description
            </dt>
            <dd class="col-sm-10">
                @Model.Description
            </dd>
            <dt class="col-sm-2">
                Title
            </dt>
            <dd class="col-sm-10">
                @Model.Title
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger mx-5" /> 
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Blog/Details.cshtml
@model Domain.Entity.Blog



<h1>Product Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
        <dt class="col-sm-2">
            Title
        </dt>
        <dd class="col-sm-10">
           @Model.Title
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mx-5">Edit</a> 
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Blog/Edit.cshtml
@model Domain.Entity.Blog



<h1>Edit Product</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
               
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="mt-5">
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Blog/Index.cshtml
@model IEnumerable<Domain.Entity.Blog>



<h1>Blog Sayafasına Hoşgeldiniz</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Add New Blog</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
               Title
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                   @item.Name
                </td>
                <td>
                   @item.Description
                </td>
                <td>
                   @item.Title
                </td>
                <td>
                    <div class="btn-group " role="group">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary m-3 ">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning  m-3">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger  m-3">Delete</a>
                        
                  </div>

                </td>
                </tr>
        }
        </table>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMvcProjectTest1/WebMvcProjectTest1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMvcProjectTest1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMvcProjectTest1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogWebSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Bloglar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Create">Yeni Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebMvcProjectTest1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>